<?php

/**
 * @var $block \BelVG\Showroom\Block\Index
 * @var $escaper \Magento\Framework\Escaper
 */

if ($block->isEnabled()) {

    $showrooms = $block->getShowrooms();

?>
<form action="/showroom/create/create" method="post" class="form">
    <fieldset class="fieldset">
        <legend class="legend"><span>Please, fill the form</span></legend><br>
        <div class="field name required">
            <label class="label" for="showroom"><span>Showroom</span></label>
            <div class="control">
                <select name="showroom_id" id="showroom">
                    <?php

                    $showroomId = $block->getShowroom();
                    foreach ($showrooms as $room) {
                        ?><option value="<?= (int)$room['showroom_id']?>"<?= $room['showroom_id'] == $showroomId ? ' selected=""' : '' ?>>
                        <?= $escaper->escapeHtml($room['name'])?><?php
                    }

                    ?>
                </select>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span>Name</span></label>
            <div class="control">
                <?php

                if ($block->isLogged()) {
                    ?><?= $escaper->escapeHtml($block->getCustomerName()) ?><?php
                } else {
                    ?><input name="name" id="name" title="Name" value="<?= $escaper->escapeHtmlAttr($block->getName()) ?>" class="input-text" type="text"><?php
                }

                ?>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span>Email</span></label>
            <div class="control">
            <?php

            if ($block->isLogged()) {
                ?><?= $escaper->escapeHtml($block->getCustomerEmail()) ?><?php
            } else {
            ?><input name="email" id="email" title="Email" value="<?= $escaper->escapeHtmlAttr($block->getEmail()) ?>" class="input-text" type="email"><?php
            }

            ?>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="date"><span>Date</span></label>
            <div class="control">
                <input name="date" id="date" title="Date" value="<?= $escaper->escapeHtmlAttr($block->getDate())?>" class="input-text" type="date">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>
<?php

}

?>
